#ifndef MANETSIMS_LINKMODEL_CONSTANTS_H
#define MANETSIMS_LINKMODEL_CONSTANTS_H

#ifndef PATHLOSS_CONSTANT_OFFSET
#define PATHLOSS_CONSTANT_OFFSET -18.8
#endif

#ifndef PATHLOSS_EXPONENT
#define PATHLOSS_EXPONENT -5.5
#endif

#define KM 1000

#endif /* MANETSIMS_LINKMODEL_CONSTANTS_H */
